2020/11/27 08:13:16 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "home/page". in C:\Users\Bakura\yii1\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('home/page')
#1 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/home/page
---
2020/11/27 08:13:25 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "homepage". in C:\Users\Bakura\yii1\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('homepage')
#1 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/homepage
---
2020/11/27 08:51:29 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "localhost:8000/index". in C:\Users\Bakura\yii1\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('localhost:8000/...')
#1 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/localhost:8000/index
HTTP_REFERER=http://localhost:8000/index.php/site/page?view=about
---
2020/11/27 08:51:32 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "localhost:8000/index". in C:\Users\Bakura\yii1\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('localhost:8000/...')
#1 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/localhost:8000/index
HTTP_REFERER=http://localhost:8000/index.php/site/page?view=about
---
2020/11/27 11:42:46 [warning] [system.web.CHttpSession] Failed to start session.
in C:\xampp\htdocs\newapp\protected\views\layouts\main.php (35)
in C:\xampp\htdocs\newapp\protected\views\layouts\column1.php (6)
in C:\xampp\htdocs\newapp\protected\controllers\SiteController.php (32)
2020/11/27 11:42:46 [warning] [system.web.CHttpSession] Failed to start session.
in C:\xampp\htdocs\newapp\protected\views\layouts\main.php (35)
in C:\xampp\htdocs\newapp\protected\views\layouts\column1.php (6)
in C:\xampp\htdocs\newapp\protected\controllers\SiteController.php (32)
2020/11/27 11:42:51 [warning] [system.web.CHttpSession] Failed to start session.
in C:\xampp\htdocs\newapp\protected\views\layouts\main.php (35)
in C:\xampp\htdocs\newapp\protected\views\layouts\column1.php (6)
in C:\xampp\htdocs\newapp\protected\controllers\SiteController.php (32)
2020/11/27 11:42:51 [warning] [system.web.CHttpSession] Failed to start session.
in C:\xampp\htdocs\newapp\protected\views\layouts\main.php (35)
in C:\xampp\htdocs\newapp\protected\views\layouts\column1.php (6)
in C:\xampp\htdocs\newapp\protected\controllers\SiteController.php (32)
2020/11/27 13:14:21 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
 in C:\Users\Bakura\yii1\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\Users\Bakura\yii1\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\Users\Bakura\yii1\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\Users\Bakura\yii1\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\Users\Bakura\yii1\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\Users\Bakura\yii1\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\Users\Bakura\yii1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\Users\Bakura\yii1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\Users\Bakura\yii1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model/index
HTTP_REFERER=http://localhost:8000/index.php/gii/model/index
---
2020/11/27 13:14:33 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
 in C:\Users\Bakura\yii1\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\Users\Bakura\yii1\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\Users\Bakura\yii1\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\Users\Bakura\yii1\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\Users\Bakura\yii1\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\Users\Bakura\yii1\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\Users\Bakura\yii1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\Users\Bakura\yii1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\Users\Bakura\yii1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model/index
---
2020/11/27 13:14:39 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
 in C:\Users\Bakura\yii1\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\Users\Bakura\yii1\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\Users\Bakura\yii1\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\Users\Bakura\yii1\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\Users\Bakura\yii1\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\Users\Bakura\yii1\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\Users\Bakura\yii1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\Users\Bakura\yii1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\Users\Bakura\yii1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model/index
---
2020/11/27 13:14:43 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
 in C:\Users\Bakura\yii1\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\Users\Bakura\yii1\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\Users\Bakura\yii1\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\Users\Bakura\yii1\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\Users\Bakura\yii1\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\Users\Bakura\yii1\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\Users\Bakura\yii1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\Users\Bakura\yii1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\Users\Bakura\yii1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model/index
HTTP_REFERER=http://localhost:8000/index.php/gii/default/index
---
2020/11/27 13:14:58 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
 in C:\Users\Bakura\yii1\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\Users\Bakura\yii1\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\Users\Bakura\yii1\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\Users\Bakura\yii1\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\Users\Bakura\yii1\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\Users\Bakura\yii1\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\Users\Bakura\yii1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\Users\Bakura\yii1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\Users\Bakura\yii1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model/index
---
2020/11/27 13:15:07 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
 in C:\Users\Bakura\yii1\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\Users\Bakura\yii1\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\Users\Bakura\yii1\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\Users\Bakura\yii1\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\Users\Bakura\yii1\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\Users\Bakura\yii1\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\Users\Bakura\yii1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\Users\Bakura\yii1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\Users\Bakura\yii1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model/index
HTTP_REFERER=http://localhost:8000/index.php/gii
---
2020/11/27 13:25:55 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'dbtestyii1' in C:\Users\Bakura\yii1\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\Users\Bakura\yii1\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\Users\Bakura\yii1\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\Users\Bakura\yii1\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\Users\Bakura\yii1\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\Users\Bakura\yii1\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\Users\Bakura\yii1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\Users\Bakura\yii1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\Users\Bakura\yii1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model/index
HTTP_REFERER=http://localhost:8000/index.php/gii/model/index
---
2020/11/27 13:30:16 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'dbytestyii1' in C:\Users\Bakura\yii1\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\Users\Bakura\yii1\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\Users\Bakura\yii1\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\Users\Bakura\yii1\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\Users\Bakura\yii1\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\Users\Bakura\yii1\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\Users\Bakura\yii1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\Users\Bakura\yii1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\Users\Bakura\yii1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model/index
HTTP_REFERER=http://localhost:8000/index.php/gii/default/index
---
2020/11/27 13:30:34 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'dbtestyii1' in C:\Users\Bakura\yii1\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\Users\Bakura\yii1\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\Users\Bakura\yii1\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\Users\Bakura\yii1\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\Users\Bakura\yii1\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\Users\Bakura\yii1\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\Users\Bakura\yii1\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\Users\Bakura\yii1\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\Users\Bakura\yii1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\Users\Bakura\yii1\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\Users\Bakura\yii1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model/index
HTTP_REFERER=http://localhost:8000/index.php/gii/default/index
---
2020/11/27 13:41:40 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "user". in C:\Users\Bakura\yii1\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#1 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/user
---
2020/11/27 13:48:59 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in C:\Users\Bakura\yii1\framework\web\CController.php:486
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CController.php(270): CController->missingAction('user')
#1 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('user')
#2 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/user
---
2020/11/27 13:49:02 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "users". in C:\Users\Bakura\yii1\framework\web\CController.php:486
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CController.php(270): CController->missingAction('users')
#1 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('users')
#2 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('site/users')
#3 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/users
---
2020/11/27 13:58:13 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "user". in C:\Users\Bakura\yii1\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#1 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/user
---
2020/11/27 13:58:20 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index/user". in C:\Users\Bakura\yii1\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('index/user')
#1 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/index/user
---
2020/11/27 13:58:35 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in C:\Users\Bakura\yii1\framework\web\CController.php:486
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CController.php(270): CController->missingAction('user')
#1 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('user')
#2 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/user
---
2020/11/27 13:58:39 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "user". in C:\Users\Bakura\yii1\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#1 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/user
---
2020/11/27 13:59:55 [error] [exception.CHttpException.403] CHttpException: You are not authorized to perform this action. in C:\Users\Bakura\yii1\framework\web\auth\CAccessControlFilter.php:183
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\Users\Bakura\yii1\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\Users\Bakura\yii1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#3 C:\Users\Bakura\yii1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\Users\Bakura\yii1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\Users\Bakura\yii1\framework\web\CController.php(291): CFilterChain->run()
#6 C:\Users\Bakura\yii1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('users/admin')
#9 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/index.php/users/admin
HTTP_REFERER=http://localhost:8000/index.php/site/login
---
2020/11/27 14:00:33 [error] [exception.CHttpException.403] CHttpException: You are not authorized to perform this action. in C:\Users\Bakura\yii1\framework\web\auth\CAccessControlFilter.php:183
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\Users\Bakura\yii1\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\Users\Bakura\yii1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#3 C:\Users\Bakura\yii1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\Users\Bakura\yii1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\Users\Bakura\yii1\framework\web\CController.php(291): CFilterChain->run()
#6 C:\Users\Bakura\yii1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('users/admin')
#9 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/index.php/users/admin
HTTP_REFERER=http://localhost:8000/index.php/site/login
---
2020/11/27 14:00:57 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in C:\Users\Bakura\yii1\framework\web\CController.php:486
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CController.php(270): CController->missingAction('user')
#1 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('user')
#2 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/user
---
2020/11/27 14:01:57 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "gii/user". in C:\Users\Bakura\yii1\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/user')
#1 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii/user
---
2020/11/27 14:09:28 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in C:\Users\Bakura\yii1\framework\web\CController.php:486
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CController.php(270): CController->missingAction('user')
#1 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('user')
#2 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/user
---
2020/11/27 14:09:32 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "users". in C:\Users\Bakura\yii1\framework\web\CController.php:486
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CController.php(270): CController->missingAction('users')
#1 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): CController->run('users')
#2 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('site/users')
#3 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/users
---
2020/11/27 14:17:51 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "gii/user". in C:\Users\Bakura\yii1\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/user')
#1 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii/user
---
2020/11/27 14:18:15 [error] [php] Array to string conversion (C:\xampp\htdocs\newapp\protected\views\site\index.php:6)
Stack trace:
#0 C:\Users\Bakura\yii1\framework\web\CBaseController.php(95): SiteController->renderInternal()
#1 C:\Users\Bakura\yii1\framework\web\CController.php(872): SiteController->renderFile()
#2 C:\Users\Bakura\yii1\framework\web\CController.php(785): SiteController->renderPartial()
#3 C:\xampp\htdocs\newapp\protected\controllers\SiteController.php(32): SiteController->render()
#4 C:\Users\Bakura\yii1\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#5 C:\Users\Bakura\yii1\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 C:\Users\Bakura\yii1\framework\web\CController.php(286): SiteController->runAction()
#7 C:\Users\Bakura\yii1\framework\web\CController.php(265): SiteController->runActionWithFilters()
#8 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(282): SiteController->run()
#9 C:\Users\Bakura\yii1\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 C:\Users\Bakura\yii1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\newapp\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php
in C:\xampp\htdocs\newapp\protected\views\site\index.php (6)
in C:\xampp\htdocs\newapp\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\newapp\index.php (13)
